### ISSUE TITLE
Update README for experimental TrueLens

### ISSUE THREAD

**Issue by RWayne93** [kesamet/retrieval-augmented-generation#25]
Basically the title. I have just started with getting into rag evaluation and came across your repo with truelens. Curious as to why gemni pro. I don't have access to pro yet.

**Comment by kesamet** [comment]
trulens documentation mainly shows usage with OpenAI models, so there is sufficient tutorials there
i am looking at alternatives and making them work with trulens

**Comment by RWayne93** [comment]
I'm interested in alternatives as well and not relying on OpenAI models.

**Comment by RWayne93** [comment]
@kesamet Really enjoying this so far i have tried adding pgvector to your framework but can't seem to get it to work. in your config i have added 

VECTORDB_TYPE: pgvector
VECTORDB_PATH: postgresql+psycopg2://postgres:mysecretpassword@localhost:5432/postgres
COLLECTION_NAME: pdf_document_chunks

then updated in app_conv.py

```python
def load_vectordb():
    if CFG.VECTORDB_TYPE == "faiss":
        return load_faiss(BASE_EMBEDDINGS)
    if CFG.VECTORDB_TYPE == "chroma":
        return load_chroma(BASE_EMBEDDINGS)
    if CFG.VECTORDB_TYPE == "pgvector":
        print("Loading pgvector")
        print(load_pgvector(BASE_EMBEDDINGS, CFG.VECTORDB_PATH, CFG.COLLECTION_NAME))
        return load_pgvector(BASE_EMBEDDINGS, CFG.VECTORDB_PATH, CFG.COLLECTION_NAME)
    raise NotImplementedError
```

vectordb.py i have added load_pgvector

```python
def load_pgvector(
    embedding_function: Embeddings, collection_name: str, connection_string: str
) -> VectorStore:
    """Loads a PGVector index from disk."""
    print(f"collection_name = {collection_name}")
    print(f"connection_string = {connection_string}")
    print(f"embedding_function = {embedding_function}")
    return PGVector(
        connection_string=connection_string,
        embedding_function=embedding_function,
        collection_name=collection_name
    )
``` 

not sure what the issue is the connection string is correct since i can see the database and a couple of inserted documents.

**Comment by kesamet** [comment]
Looks right to me. If you can also include how you save docs to postgres, that would be great.
What is saved in metadata is dependent on user, one can choose not to save page number

**Comment by RWayne93** [comment]
> Looks right to me. If you can also include how you save docs to postgres, that would be great.
> 
> What is saved in metadata is dependent on user, one can choose not to save page number

I will. It was a little challenging at first I had to include my own uuid in the metadata for each chunk as well (I need this for a dataset I'm putting together) Postgres assigns one internally however when I use the retriever it isn't included and I couldn't figure out how to get the uuids returned to me that are generated by Postgres.

**Comment by RWayne93** [comment]
@kesamet hey man getting ready to submit a PR soon I created a fork and made a poetry branch for users that want to use poetry instead of conda. Also this is my first time using langchain this much and was wondering how exactly do you return the relevance_score with the base retriever similar to reranker retriever. That one the scores are returned in the metadata but base_retriever they are not. I have tried a few things like a ScoredRetrievalQA class with no luck. 
I've read through the docs and don't see how i am suppose to get the scores from the base retriever. 

```python
def build_base_retriever(vectordb: VectorStore) -> VectorStoreRetriever:
    retriever = vectordb.as_retriever(
        search_kwargs={"k": CFG.BASE_RETRIEVER_CONFIG.SEARCH_K},
       # search_type="similarity",
    )
    print(f"here is the retriever: {retriever}")
    return retriever
```

**Comment by kesamet** [comment]
We could probably write a wrapper of VectorStoreRetriever that can also output scores in the metadata field. I can help do that

**Comment by RWayne93** [comment]
@kesamet random but i'm looking for a way to use llama.cpp's openai restful api server. i have it setup like this but for some reason it doesn't want to play nice with the rest of the features in langchain... 

```python
"""
LLM
"""
import os
from typing import Optional

from langchain_community.llms.ctransformers import CTransformers
from langchain_community.llms.llamacpp import LlamaCpp
from langchain_community.llms.openai import OpenAI
from langchain.callbacks import StreamingStdOutCallbackHandler
from langchain_openai import ChatOpenAI

from src import CFG
from src.helpers.findenv import load_env


def build_llm():
    """Builds LLM defined in config."""
    if CFG.USE_OPENAI:
        load_env()
        return build_openai(
            model_name=CFG.LLM_PATH,
            config={
                "max_tokens": CFG.LLM_CONFIG.MAX_NEW_TOKENS,
                "temperature": CFG.LLM_CONFIG.TEMPERATURE,
                "repetition_penalty": CFG.LLM_CONFIG.REPETITION_PENALTY,
            },
        )
    elif CFG.USE_CTRANSFORMERS:
        return build_ctransformers(
            os.path.join(CFG.MODELS_DIR, CFG.LLM_PATH),
            config={
                "max_new_tokens": CFG.LLM_CONFIG.MAX_NEW_TOKENS,
                "temperature": CFG.LLM_CONFIG.TEMPERATURE,
                "repetition_penalty": CFG.LLM_CONFIG.REPETITION_PENALTY,
                "context_length": CFG.LLM_CONFIG.CONTEXT_LENGTH,
            },
        )
    elif CFG.USE_LLAMACPP_SERVER:  # Configuration to use the LlamaCpp server
        return build_llamacpp_server(
            CFG.LLM_PATH,  # You'll need to define this in your configuration
            config={
                "max_tokens": CFG.LLM_CONFIG.MAX_NEW_TOKENS,
                "temperature": CFG.LLM_CONFIG.TEMPERATURE,
                "repeat_penalty": CFG.LLM_CONFIG.REPETITION_PENALTY,
                "n_ctx": CFG.LLM_CONFIG.CONTEXT_LENGTH,
                # "n_gpu_layers": CFG.LLM_CONFIG.N_GPU_LAYERS, # Uncomment if applicable
            }
        )
    else:
        # Default to a standard LlamaCpp setup
        config = {
            "max_tokens": CFG.LLM_CONFIG.MAX_NEW_TOKENS,
            "temperature": CFG.LLM_CONFIG.TEMPERATURE,
            "repeat_penalty": CFG.LLM_CONFIG.REPETITION_PENALTY,
            "n_ctx": CFG.LLM_CONFIG.CONTEXT_LENGTH,
        }
        if CFG.DEVICE != "cpu":
            config["n_gpu_layers"] = CFG.LLM_CONFIG.N_GPU_LAYERS

        return build_llamacpp(
            os.path.join(CFG.MODELS_DIR, CFG.LLM_PATH),
            config=config,
        )


def build_ctransformers(
    model_path: str, config: Optional[dict] = None, debug: bool = False, **kwargs
):
    """Builds LLM using CTransformers."""
    if config is None:
        config = {
            "max_new_tokens": 512,
            "temperature": 0.2,
            "repetition_penalty": 1.1,
            "context_length": 1024,
        }

    llm = CTransformers(
        model=model_path,
        config=config,
        callbacks=[StreamingStdOutCallbackHandler()] if debug else None,
        **kwargs,
    )
    return llm

def build_openai(model_name: str, config: Optional[dict] = None, **kwargs):
    """Builds LLM using OpenAI."""
    if config is None:
        config = {
            "max_tokens": 512,
            "temperature": 0.2,
            "repetition_penalty": 1.1,
        }

    llm = OpenAI(model_name=model_name, **config, **kwargs)
    return llm


def build_llamacpp_server(endpoint: str, config: Optional[dict] = None, **kwargs):
    """Builds LLM using LlamaCpp."""
    if config is None:
        config = {
            "max_tokens": 512,
            "temperature": 0.2,
            "repeat_penalty": 1.1,
            "n_ctx": 2048,
           # "n_gpu_layers": -1
        }

    llm = ChatOpenAI(
        endpoint=endpoint,
        model_name="model_deployed",
        openai_api_key="sk-no-key-required",
        **config,
        #callbacks=[StreamingStdOutCallbackHandler()] if debug else None,
        **kwargs
    )
    return llm

def build_llamacpp(
    model_path: str, config: Optional[dict] = None, debug: bool = False, **kwargs
):
    """Builds LLM using LlamaCpp."""
    if config is None:
        config = {
            "max_tokens": 512,
            "temperature": 0.2,
            "repeat_penalty": 1.1,
            "n_ctx": 2048,
            "n_gpu_layers": -1
        }

    llm = LlamaCpp(
        model_path=model_path,
        **config,
        callbacks=[StreamingStdOutCallbackHandler()] if debug else None,
        **kwargs,
    )
    return llm
```

Traceback (most recent call last):
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 542, in _run_script
    exec(code, module.__dict__)
  File "/home/archie/retrieval-augmented-generation/app_qa.py", line 245, in <module>
    doc_qa()
  File "/home/archie/retrieval-augmented-generation/app_qa.py", line 194, in doc_qa
    st.session_state.last_response = retrieval_qa.invoke(
                                     ^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/retrieval_qa/base.py", line 144, in _call
    answer = self.combine_documents_chain.run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 574, in run
    return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 378, in __call__
    return self.invoke(
           ^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/combine_documents/base.py", line 137, in _call
    output, extra_return_dict = self.combine_docs(
                                ^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/combine_documents/stuff.py", line 244, in combine_docs
    return self.llm_chain.predict(callbacks=callbacks, **inputs), {}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 293, in predict
    return self(kwargs, callbacks=callbacks)[self.output_key]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_core/_api/deprecation.py", line 145, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 378, in __call__
    return self.invoke(
           ^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 163, in invoke
    raise e
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/base.py", line 153, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 103, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain/chains/llm.py", line 115, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 556, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 417, in generate
    raise e
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 407, in generate
    self._generate_with_cache(
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 626, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 548, in _generate
    response = self.client.create(messages=message_dicts, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/archie/.cache/pypoetry/virtualenvs/rag-demo-2HUgQS9K-py3.11/lib/python3.11/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
TypeError: Completions.create() got an unexpected keyword argument 'endpoint'

**Comment by kesamet** [comment]
cosine distance to be exact, not cosine similarity
